# ALIYUN SLS
aliyun.sls.disabled=YES
aliyun.sls.project=
aliyun.sls.logstore=
aliyun.sls.endpoint=cn-hangzhou-intranet.log.aliyuncs.com
aliyun.sls.accessKeyId=
aliyun.sls.accessKeySecret=
table.package.path=
mysql.default_data_source_name=akagi
mysql.akagi.host=study-hub-test.rwlb.rds.aliyuncs.com
mysql.akagi.port=3306
mysql.akagi.username=togo
mysql.akagi.password=**
mysql.akagi.schema=drydock_lesson
mysql.akagi.charset=utf8mb4
mysql.akagi.poolMaxSize=16
mysql.akagi.poolShared=YES
mysql.akagi.connectionTimeout=2000
mysql.akagi.poolConnectionTimeout=2

