katori.counting_down=5

# ALIYUN SLS
aliyun.sls.disabled=YES
aliyun.sls.project=
aliyun.sls.logstore=
aliyun.sls.endpoint=cn-hangzhou-intranet.log.aliyuncs.com
aliyun.sls.accessKeyId=
aliyun.sls.accessKeySecret=
mysql.default_data_source_name=drydock_lesson
mysql.drydock_lesson.host=study-hub-test.rwlb.rds.aliyuncs.com
mysql.drydock_lesson.port=3306
mysql.drydock_lesson.username=togo
mysql.drydock_lesson.password=**
mysql.drydock_lesson.schema=drydock_lesson
mysql.drydock_lesson.charset=utf8mb4
mysql.drydock_lesson.poolMaxSize=16
mysql.drydock_lesson.poolShared=YES
mysql.drydock_lesson.connectionTimeout=2000
mysql.drydock_lesson.poolConnectionTimeout=2

